dist: trusty
sudo: false
language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-test
    - python: 3.4
      env: TOXENV=py34-test
    - python: 3.5
      env: TOXENV=py35-test
    - python: 3.6
      env: TOXENV=py36-test
    - python: 3.7
      env: TOXENV=py37-test
      # 3.7 requires sudo: https://github.com/travis-ci/travis-ci/issues/9831
      sudo: required
      dist: xenial
    - python: 3.6
      env: TOXENV=py36-docs
    - python: 3.6
      env: TOXENV=py36-doctest

install:
  - pip install -U tox

script:
  - tox
